require('ts-node').register({ files: true });
const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const { findDuplicates } = require('../src/main/duplicates');
const db = new DatabaseSync(':memory:');
db.exec(`CREATE TABLE files (id INTEGER PRIMARY KEY, path TEXT, name TEXT, size INTEGER,
  placement INTEGER, missing INTEGER DEFAULT 0);
  CREATE INDEX idx_name_size ON files(name, size);`);
const add = db.prepare('INSERT INTO files (path, name, size, placement, missing) VALUES (?, ?, ?, ?, ?)');
add.run('backup/renamed.MP4', 'renamed.MP4', 100, 0, 0);
add.run('library/original.mov', 'original.mov', 100, 2, 0);
add.run('month/clip.mkv', 'clip.mkv', 100, 1, 0);
add.run('photos/a.jpg', 'a.jpg', 100, 2, 0);
add.run('backup/absent.mp4', 'absent.mp4', 100, 0, 1);
add.run('single/clip.mp4', 'clip.mp4', 200, 0, 0);
add.run('single/image.jpg', 'image.jpg', 200, 0, 0);
add.run('backup/same.mp4', 'same.mp4', 300, 0, 0);
add.run('library/same.mp4', 'same.mp4', 301, 2, 0);
const videos = findDuplicates('video-size', db);
assert.equal(videos.length, 1);
assert.equal(videos[0].size, 100);
assert.deepEqual(videos[0].files.map(f => f.placement), [2, 1, 0]);
assert.deepEqual(videos[0].files.map(f => f.path), ['library/original.mov', 'month/clip.mkv', 'backup/renamed.MP4']);
assert.equal(findDuplicates('name-size', db).length, 0);
const names = findDuplicates('name', db);
assert.equal(names.length, 1);
assert.equal(names[0].name, 'same.mp4');
assert.deepEqual(names[0].files.map(f => f.placement), [2, 0]);
assert.throws(() => findDuplicates('unknown', db));
db.close();
console.log('Duplicates: renamed videos, extensions, ranks, sizes, missing files and existing modes passed');
