require('ts-node').register({ files: true });
const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const { findDuplicates } = require('../src/main/duplicates');
const db = new DatabaseSync(':memory:');
db.exec(`CREATE TABLE files (id INTEGER PRIMARY KEY, path TEXT, name TEXT, size INTEGER,
  placement INTEGER, missing INTEGER DEFAULT 0);
  CREATE INDEX idx_name_size ON files(name, size);`);
const add = db.prepare('INSERT INTO files (path, name, size, placement, missing) VALUES (?, ?, ?, ?, ?)');
add.run('backup/renamed.MP4', 'renamed.MP4', 100, 0, 0);
add.run('library/original.mov', 'original.mov', 100, 2, 0);
add.run('month/clip.mkv', 'clip.mkv', 100, 1, 0);
add.run('photos/a.jpg', 'a.jpg', 100, 2, 0);
add.run('backup/absent.mp4', 'absent.mp4', 100, 0, 1);
add.run('single/clip.mp4', 'clip.mp4', 200, 0, 0);
add.run('single/image.jpg', 'image.jpg', 200, 0, 0);
add.run('backup/same.mp4', 'same.mp4', 300, 0, 0);
add.run('library/same.mp4', 'same.mp4', 301, 2, 0);
const videos = findDuplicates('video-size', db);
assert.equal(videos.length, 1);
assert.equal(videos[0].size, 100);
assert.deepEqual(videos[0].files.map(f => f.placement), [2, 1, 0]);
assert.deepEqual(videos[0].files.map(f => f.path), ['library/original.mov', 'month/clip.mkv', 'backup/renamed.MP4']);
assert.equal(findDuplicates('name-size', db).length, 0);
const names = findDuplicates('name', db);
assert.equal(names.length, 1);
assert.equal(names[0].name, 'same.mp4');
assert.deepEqual(names[0].files.map(f => f.placement), [2, 0]);
add.run('backup/repeated.mp4', 'repeated.mp4', 400, 0, 0);
add.run('library/repeated.mp4', 'repeated.mp4', 400, 2, 0);
add.run('missing/renamed.mp4', 'renamed.mp4', 400, 0, 1);
add.run('photos/different.jpg', 'different.jpg', 400, 0, 0);
assert.equal(findDuplicates('video-size', db).length, 1, 'Same names, missing videos and images must not create video-size groups');
assert.equal(findDuplicates('name-size', db).find(g => g.name === 'repeated.mp4').files.length, 2);
add.run('month/new-name.mp4', 'new-name.mp4', 400, 1, 0);
const renamedGroup = findDuplicates('video-size', db).find(g => g.size === 400);
assert.deepEqual(renamedGroup.files.map(f => f.path),
  ['library/repeated.mp4', 'month/new-name.mp4', 'backup/repeated.mp4']);
assert.throws(() => findDuplicates('unknown', db));
add.run('dvd/VTS_01_1.VOB', 'VTS_01_1.VOB', 500, 1, 0);
add.run('legacy/BUSHU.ASF', 'BUSHU.ASF', 500, 0, 0);
assert.equal(findDuplicates('video-size', db).find(g => g.size === 500).files.length, 2);
db.close();
console.log('Duplicates: renamed videos, extensions, ranks, sizes, missing files and existing modes passed');
